### PR TITLE
Update cargo dep, bump version

### LINKED ISSUE #31: Fails to build with error in cargo-0.47.0
When building on macOS with Rust 1.49 (from `cargo install cargo-instruments`):

```rust
error[E0283]: type annotations needed
   --> /Users/djc/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-0.47.0/src/cargo/util/config/de.rs:491:63
    |
491 |                 seed.deserialize(Tuple2Deserializer(1i32, env.as_ref()))
    |                                                           ----^^^^^^--
    |                                                           |   |
    |                                                           |   cannot infer type for type parameter `T` declared on the trait `AsRef`
    |                                                           this method call resolves to `&T`
    |
    = note: cannot satisfy `std::string::String: AsRef<_>`
```

### PR DESCRIPTION
**Pull request by cmyr**
closes #31 (folks may have to build from source until I do a release; I'd like to wait for #29 to do a release, if feasible)

### CODE REVIEW

**Comment by cmyr** [comment]
This is superseded by #33
