### ISSUE TITLE
Fails to build with error in cargo-0.47.0

### ISSUE THREAD

**Issue by djc** [cmyr/cargo-instruments#31]
When building on macOS with Rust 1.49 (from `cargo install cargo-instruments`):

```rust
error[E0283]: type annotations needed
   --> /Users/djc/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-0.47.0/src/cargo/util/config/de.rs:491:63
    |
491 |                 seed.deserialize(Tuple2Deserializer(1i32, env.as_ref()))
    |                                                           ----^^^^^^--
    |                                                           |   |
    |                                                           |   cannot infer type for type parameter `T` declared on the trait `AsRef`
    |                                                           this method call resolves to `&T`
    |
    = note: cannot satisfy `std::string::String: AsRef<_>`
```

**Comment by cmyr** [comment]
thanks, looks like I need to update the cargo dep.

**Comment by cmyr** [comment]
This is fixed in #33.
